version: '3'
 
services:
  app:
    build:
      context:  ./frontend
      dockerfile: Dockerfile
    environment:
        - HOST_IP=159.65.237.246
    expose:
      - "5000"
  graphql:
    build:
      context:  ./backend
      dockerfile: Dockerfile
    expose:
      - "4000"
  proxy:
    build:
      context:  ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    links:
      - app
      - graphql
